import { Analytics } from '@vercel/analytics/react'
import { SpeedInsights } from '@vercel/speed-insights/next'

import './globals.css'

export const metadata = {
  description: 'Generated by Next.js',
  title: 'themeaningof8'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html className="scroll-smooth" lang="ja">
      <body className="bg-background text-foreground dark:bg-background-dark dark:text-foreground-dark overflow-y-scroll">
        <header>あああ</header>
        <main className="mx-6 my-10">
          <div className="prose dark:prose-invert mx-auto">{children}</div>
        </main>
        <Analytics />
        <SpeedInsights />
        <footer>あああ</footer>
      </body>
    </html>
  )
}
