import { Analytics } from '@vercel/analytics/react';
import "../styles/globals.css";

export const metadata = {
  title: "themeaningof8",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <Analytics />
      <body className="overflow-y-scroll">
        <div className="mx-6 my-10">
          <div className="prose mx-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}