import clsx from "clsx";
import { Analytics } from '@vercel/analytics/react';
import { IBM_Plex_Mono, IBM_Plex_Sans } from "next/font/google";
import "../styles/globals.css";

const mono = IBM_Plex_Mono({
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-ibm-plex-mono",
  subsets: ["latin"]
});

const sans = IBM_Plex_Sans({
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-ibm-plex-sans",
  subsets: ["latin"]
});

export const metadata = {
  title: "themeaningof8",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={clsx(sans.variable, mono.variable, "scroll-smooth")}>
      <Analytics />
      <body className="overflow-y-scroll">
        <div className="mx-6 my-10">
          <div className="prose mx-auto">{children}</div>
        </div>
      </body>
    </html>
  );
}