import '@styles/index.css'
import { Analytics } from '@vercel/analytics/react'

export const metadata = {
  description: 'Generated by Next.js',
  title: 'themeaningof8',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="scroll-smooth" lang="en">
      <Analytics />
      <body className="overflow-y-scroll">
        <div className="mx-6 my-10">
          <div className="prose mx-auto">{children}</div>
        </div>
      </body>
    </html>
  )
}
